### ISSUE TITLE
provider/provider.js: No such file or directory

### ISSUE THREAD

**Issue by devgaurav500** [humaniq/humaniq-mobile#131]
i cloned this repo and installing node modules by using yarn but i was getting this error
`cp: provider/provider.js: No such file or directory
error Command failed with exit code 1.`

![Screenshot 2022-05-25 at 6 06 10 PM](https://user-images.githubusercontent.com/106137633/170263330-3c9b4de2-42af-41fb-9bb2-755b44241ddd.png)

**Comment by thisroot** [comment]
It's normally, this command need if you use ios for building platform

**Comment by devgaurav500** [comment]
how do i resolve it, i also tried using NPM but also got error

**Comment by DjamshidDjurayev** [comment]
@devgaurav500 as a workaround you can just manually copy provider.js from android/app/src/main/assets/provider.js to provider folder

**Comment by DjamshidDjurayev** [comment]
@devgaurav500 if there is no provider folder in the root project, just create it and paste provider.js copied from android/app/src/main/assets/provider.js.  It's generated after npm or yarn install. It will be fixed in the next release
